Feature support multiple test cases
mjirv/dbt-datamocktool pull request #54
Opened 2022-09-30 15:24 UTC by marcellovictorino

This is a:
- [ ] bug fix PR with no breaking changes
- [x] new functionality
- [ ] a breaking change

## Description & motivation
Addressing [this issue](https://github.com/mjirv/dbt-datamocktool/issues/53), enables to define a test once, to be applied over multiple test cases.

Applicable when there are multiple test case scenarios, where the mocked input and expected output data (seed) represent a single case, having the seed file names identified by `test_case_1`, `test_case_2` etc.

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [x] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my macros (and models if applicable) -> added descriptions. Not sure how to add tests

## Additional comments
1. I am not sure what is the best way to adapt the proposed code change to the new dispatch pattern. I developed these changes against an old package version (`v 0.1.2`). I marked it with the comment `{% FIXME: ...`

2. Also, I have changed the `get_test` macro behavior to always store the mocked model output as a view, which provides better visibility on failing tests. As a `view`, it is possible to inspect its definition, quickly debugging any issues

> **Note**: this is my first time contributing to an open-source project 🎉! Please let me know if there is anything else I could/should do 👍

2022-10-03 09:59 UTC, marcellovictorino commented
Forgot to tag you here for visibility:
@mjirv

2022-10-03 10:00 UTC, marcellovictorino commented on README.md
> +TODO: if storing result as a view, it is possible to inspect the mocked model code, making it easier to debug issues with failing tests.
To be further fleshed out if okay to move forward with storing mocked model output

2022-10-03 10:01 UTC, marcellovictorino commented on macros/dmt_get_test_sql.sql
> +        {# {% set mock_model_relation = dbt_datamocktool._get_model_to_mock(
@mjirv would appreciate your support here, as I am not sure what is the best way to proceed with the dispatch pattern
Should I change all cases to make them store the mocked model output as a view as well?

2022-10-03 10:03 UTC, marcellovictorino commented on macros/dmt_get_test_sql.sql
> +                    type='view') %}
Note: this `model.database/schema` will get the reference from the model where the test is being applied
Instead, I wanted to get the default value as defined in the dbt_project.yml file. Any idea how to achieve this?

In my particular use case, I was able to just hard-code the values, but would be nice to have something more elegant

2022-10-03 10:06 UTC, marcellovictorino commented on macros/dmt_get_test_sql.sql
> +                    type='view') %}
This `model.database/schema` will retrieve the value from the model where the test is being applied.
Alternatively, I wanted to use the default value as defined in the `dbt_project.yaml`, for the seeds. Any idea how to do this?

In my use case, I was able to hard-code the value, but would be nice to have a more elegant solution

2022-10-05 23:01 UTC, mjirv requested changes
Hey @marcellovictorino. Thanks again for submitting this. Great work, and it will be an awesome feature to add.

I left a few comments in the code. Curious to get your thoughts.

Also, I'm finding it a little hard to review _both_ the "multiple test case" feature and the "save output for inspection" feature all at once. Could you split them into 2 separate PRs?

2022-10-11 13:50 UTC, marcellovictorino commented on macros/dmt_unit_test.sql
> +        {% set test_sql = custom_get_unit_test_sql(model, input_mapping) %}
My bad! That was my mistake, pointing to the wrong function/macro (the one I cloned and modified locally)
Will fix this. Thanks!

2022-10-11 13:50 UTC, marcellovictorino commented on macros/dmt_unit_test.sql
> +{% test unit_test(model, input_mapping, expected_output, test_case_list = []) %}
Good point! I will fix this as well

2022-10-11 13:51 UTC, marcellovictorino commented
Thanks for the review @mjirv . I really appreciate it :)
Been a busy week, but I will perform the required changes before the end of the week (2022-10-14)

2022-10-14 16:11 UTC, marcellovictorino commented on README.md
> +  - [Visibility on test failure](#visibility-on-test-failure)
fixed

2022-10-14 16:45 UTC, marcellovictorino commented on macros/dmt_unit_test.sql
> +    {% if test_case_list %}
I thought pushing the string substitution into a separate function would decouple/make things easier. But it seems fine to leave in the main body - which is easier to understand where the parameters are being used 👍

2022-10-14 17:07 UTC, marcellovictorino commented
Closing this in favor of splitting the different features into separate PRs: https://github.com/mjirv/dbt-datamocktool/pull/56

2022-10-14 17:07 UTC, marcellovictorino commented
Closing this in favor of splitting the different features into separate PRs: https://github.com/mjirv/dbt-datamocktool/pull/56

2022-10-14 17:07 UTC, closed without merging